/* Generated By:JavaCC: Do not edit this line. ParserTreeConstants.java Version 5.0 */
package grammar;

public interface ParserTreeConstants
{
  public int JJTSTART = 0;
  public int JJTPROGRAM = 1;
  public int JJTSENTENCEBLOCK = 2;
  public int JJTSENTENCE = 3;
  public int JJTSEQUENCESENT = 4;
  public int JJTCONDITIONSENT = 5;
  public int JJTLOOPSENT = 6;
  public int JJTDECLARESENT = 7;
  public int JJTASSIGMENTSENT = 8;
  public int JJTCONDITION = 9;
  public int JJTEXPRESSION = 10;
  public int JJTADDITIVEEXPRESSION = 11;
  public int JJTMULTIPLICATIVEEXPRESSION = 12;
  public int JJTUNARYEXPRESSION = 13;
  public int JJTIDENTIFIER = 14;
  public int JJTINTEGER = 15;
  public int JJTRELATIONS = 16;
  public int JJTRETURNSENT = 17;


  public String[] jjtNodeName = {
    "Start",
    "Program",
    "SentenceBlock",
    "Sentence",
    "SequenceSent",
    "ConditionSent",
    "LoopSent",
    "DeclareSent",
    "AssigmentSent",
    "Condition",
    "Expression",
    "AdditiveExpression",
    "MultiplicativeExpression",
    "UnaryExpression",
    "Identifier",
    "Integer",
    "Relations",
    "ReturnSent",
  };
}
/* JavaCC - OriginalChecksum=eae5ce7a559d3bd89e76e07bf26c9fd1 (do not edit this line) */
